### ISSUE TITLE
issues with images with no manifest

### ISSUE THREAD

**Issue by chicco785** [Chizkiyahu/delete-untagged-ghcr-action#22]
Apparently (for whatever reason) some images are generated with no manifest, and this causes the action to fail.

```
Run Chizkiyahu/delete-untagged-ghcr-action@v2
  with:
    token: ***
    repository_owner: zaphiro-technologies
    repository: zaphiro-technologies/data-download-backend
    untagged_only: true
    owner_type: org
    except_untagged_multiplatform: true
Run actions/setup-python@v4
Installed versions
Run pip install -r /home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v[2](https://github.com/zaphiro-technologies/data-download-backend/actions/runs/5209690471/jobs/9400797548#step:3:2)/requirements.txt
Collecting requests (from -r /home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v2/requirements.txt (line 1))
  Downloading requests-2.[3](https://github.com/zaphiro-technologies/data-download-backend/actions/runs/5209690471/jobs/9400797548#step:3:3)1.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 2.1 MB/s eta 0:00:00
Collecting charset-normalizer<[4](https://github.com/zaphiro-technologies/data-download-backend/actions/runs/5209690471/jobs/9400797548#step:3:4),>=2 (from requests->-r /home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v2/requirements.txt (line 1))
  Downloading charset_normalizer-3.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 kB 3.3 MB/s eta 0:00:00
Collecting idna<4,>=2.[5](https://github.com/zaphiro-technologies/data-download-backend/actions/runs/5209690471/jobs/9400797548#step:3:5) (from requests->-r /home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v2/requirements.txt (line 1))
  Downloading idna-3.4-py3-none-any.whl ([6](https://github.com/zaphiro-technologies/data-download-backend/actions/runs/5209690471/jobs/9400797548#step:3:6)1 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 10.1 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1 (from requests->-r /home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v2/requirements.txt (line 1))
  Downloading urllib3-2.0.3-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.6/123.6 kB 8.[7](https://github.com/zaphiro-technologies/data-download-backend/actions/runs/5209690471/jobs/9400797548#step:3:7) MB/s eta 0:00:00
Collecting certifi>=2017.4.17 (from requests->-r /home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v2/requirements.txt (line 1))
  Downloading certifi-2023.5.7-py3-none-any.whl (156 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.0/157.0 kB 10.9 MB/s eta 0:00:00
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2023.5.7 charset-normalizer-3.1.0 idna-3.4 requests-2.31.0 urllib3-2.0.3

Notice:  A new release of pip is available: 22.0.4 -> 23.1.2
Notice:  To update, run: pip install --upgrade pip
Run args="--token *** "
args: --token ***  --repository_owner zaphiro-technologies  --repository zaphiro-technologies/data-download-backend  --untagged_only true  --except_untagged_multiplatform true  --owner_type org 
docker manifest inspect ghcr.io/zaphiro-technologies/data-download-api@sha256:023a074442207c9901a415ecb927b[8](https://github.com/zaphiro-technologies/data-download-backend/actions/runs/5209690471/jobs/9400797548#step:3:8)c5eca7e74e87bb26b745ff4772b6e3dce7
Traceback (most recent call last):
  File "/home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v2/clean_ghcr.py", line 231, in <module>
    delete_pkgs(
  File "/home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v2/clean_ghcr.py", line 131, in delete_pkgs
    deps_pkgs = get_deps_pkgs(owner, tagged_pkgs)
  File "/home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v2/clean_ghcr.py", line [9](https://github.com/zaphiro-technologies/data-download-backend/actions/runs/5209690471/jobs/9400797548#step:3:10)5, in get_deps_pkgs
    ids.extend(get_image_deps(image))
  File "/home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v2/clean_ghcr.py", line 100, in get_image_deps
    manifest_txt = get_manifest(image)
  File "/home/runner/work/_actions/Chizkiyahu/delete-untagged-ghcr-action/v2/clean_ghcr.py", line 110, in get_manifest
    raise Exception(res.stderr)
Exception: b'no such manifest: ghcr.io/zaphiro-technologies/data-download-api@sha256:023a074442207c9901a[41](https://github.com/zaphiro-technologies/data-download-backend/actions/runs/5209690471/jobs/9400797548#step:3:45)5ecb927b8c5eca7e74e87bb26b7[45](https://github.com/zaphiro-technologies/data-download-backend/actions/runs/5209690471/jobs/9400797548#step:3:49)ff[47](https://github.com/zaphiro-technologies/data-download-backend/actions/runs/5209690471/jobs/9400797548#step:3:51)[72](https://github.com/zaphiro-technologies/data-download-backend/actions/runs/5209690471/jobs/9400797548#step:3:77)b6e3dce7\n'
Error: Process completed with exit code 1.
```

Would it make sense to simply simply move to the next image and report warning for these cases?

**Comment by RomuloPBenedetti** [comment]
Provenance information is probably the cause of your problem, give a look [here](https://github.com/orgs/community/discussions/45779)

`docker manifest inspect` seams to fail to parse images with the `attestation-manifest`.
